language: python
python:
  - 2.7
  - 3.4
  - 3.5
install:
  - pip install coveralls
  - pip install nose
  - pip install six
script:
  coverage run --source=taxon_names_resolver setup.py test
after_success:
  coveralls
